### ISSUE TITLE
Enviar email quando usuário se cadastrar

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/atendimento#16]
Enviar email quando usuário se cadastrar no sistema.

**Comment by LucianoAlmeida** [comment]
Devo enviar para quem se cadastrou apenas ou pra algum administrador também? O que devo enviar na mensagem, algum tipo de validação?

**Comment by edwardoliveira** [comment]
Boa pergunta. Falei com o Fábio e ele falou que só precisa enviar pra pessoa que se cadastrou. Acho que devemos colocar algum tipo de validação do tipo "clique aqui para validar o email".
